### ISSUE TITLE
-w option does not work

### ISSUE THREAD

**Issue by cmungall** [ihh/bracery#62]
```
./bin/bracery -w -e '~common_animal'
invalid option w
```

**Comment by ihh** [comment]
Are you up-to-date? The latest versions on github and npm both parse the `-w` option (though it is broken for another reason, namely I haven't yet hooked up the `/api/v1/expand` route in API Gateway; the introduction of user-namespaced symbols, which is not covered in the README yet, broke a lot of that online stuff, and I have yet to fix all of it)

**Comment by cmungall** [comment]
same issue as #63
