### ISSUE TITLE
Clarify REPL interpretation of assignments

### ISSUE THREAD

**Issue by cmungall** [ihh/bracery#63]
This example from the README works:

```
$ ./bin/bracery -r
enter Bracery text for expansion:
[greetings=>hello|well met|how goes it|greetings]

[wizard=>wizard|witch|mage|magus|magician|sorcerer|enchanter]

[earthsea=>earthsea|Earth|Middle Earth|the planet|the world]

#greetings#, #wizard# of #earthsea#
how goes it, wizard of earthsea
```

in contrast to:

```
$ ./bin/bracery -r
enter Bracery text for expansion:
$greetings=[hello|well met|how goes it|greetings]
=how goes it
$wizard=[wizard|witch|mage|magus|magician|sorcerer|enchanter]
=witch
$earthsea=[earthsea|Earth|Middle Earth|the planet|the world]
=earthsea
$greetings, $wizard of $earthsea
,  of 
```

The REPL context seems to be directly evaluating, but it's not totally clear from the README what can be executed in a REPL context vs loading a program and evaluating

**Comment by ihh** [comment]
i strongly suspect you have a buggy version that somehow snuck into npm, or something; the second version works for me. Can you pull/update and try again?

**Comment by cmungall** [comment]
aha, yes, I didn't notice this at the end of the stdout after my git pull:

`fatal: refusing to merge unrelated histories`

which is odd as I never made any modifications, but blowing away and re-cloning fixes things

**Comment by ihh** [comment]
yeah i messed up the history at some point i think, huh
